### ISSUE TITLE
[Question] Is there no way to separate a minecart from a chest/hopper/tnt/furnace with this mod installed?

### ISSUE THREAD

**Issue by SplendidAlakey** [altrisi/DropFullCarts#1]
I understand the purpose of the mod and that it's a good QoL improvement for big farms, but also having no way to separate the minecarts from it's items at all feels kind of awkward. Unless I'm missing something, could you perhaps add 4 recipes that are as simple as "insert a chest/hopper/tnt/furnace minecart into the crafting table = get a minecart and the respective item back"?

**Comment by altrisi** [comment]
There's not, actually. My reasoning was that most stuff in minecraft works this way: once you craft something, it's stays like that.

The issue with crafting recipes is that they can only give you one output, so you'd loose either the cart or the component, which doesn't sound really good. To fix it that and allow the cart to stay behind (like milk for cakes) I'd have to modify item registration and it'd make any recipe keep those, potentially breaking datapacks or other mods recipes and making it way more invasive. And I know a bunch of people using this that don't want unnecessary modifications/recipes anyway.

There's not really an easy way to get this tbh from an user-only perspective, given if you make a custom recipe with a datapack or one of those online recipe generators you'll always loose one of the components.

**Comment by SplendidAlakey** [comment]
Oh, alright, I didn't know about the limitations of recipes. Will be interesting to see how Mojang decides to handle it in 1.19, but I assume it will be exactly the same. Thanks for the reply!
